version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "23:15"
    timezone: "Asia/Kathmandu"
  open-pull-requests-limit: 10
  reviewers:
    - "zoras"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
    time: "23:15"
    timezone: "Asia/Kathmandu"
  open-pull-requests-limit: 10
  reviewers:
    - "zoras"
