version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  reviewers:
  - zoras
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.19.0
  - dependency-name: rubocop
    versions:
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:15"
  open-pull-requests-limit: 10
  reviewers:
  - zoras
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.23.0
    - 7.24.0
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.2
    - 5.2.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
