# https://raw.githubusercontent.com/bbatsov/rubocop/master/config/enabled.yml
# http://rubocop.readthedocs.io/en/latest/
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - vendor/**/* # Ignore Travis-CI build directory
    - Guardfile
  DisplayCopNames:
    enabled: true

Lint:
  Enabled: true

# Rails:
#   Enabled: false

Layout/LineLength:
  IgnoredPatterns: ['\A#'] # make rubocop ignore comments using regex
